### PR TITLE
Fix/embedded-imgs

### PR DESCRIPTION
**Pull request by gnikit**
There was an issue with static assets not being properly copied in
the sphinx documentation. The assets have now been moved to
`_static` to ensure that sphinx is able to copy them during build.
The Jupyter notebooks use the images from `_static`.

### CODE REVIEW

**Comment by gnikit** [comment]
Tested locally that all notebooks run to completion and produce the correct output.
See here https://recode-mcmcff-fork.readthedocs.io/ how the docs now, look with images correctly resolved.

**Comment by TomHodson** [comment]
Looks good, that's probably the cleanest solution!

**Comment by gnikit** [comment]
There are a few more minor issues we need to address and this should then be done.

**Comment by TomHodson** [comment]
Looking great!
________________________________

**Pull request merged**
